using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;
using Model;

namespace DAL
{
    public class CKGLInitializer :
        DropCreateDatabaseIfModelChanges<CKGLContext>
    {
        protected override void Seed(CKGLContext context)
        {
            var users = new List<User>
            {
                new User{ Auth=0, Pwd="111111", UserName="admin"},
                new User{ Auth=1,Pwd="123456",UserName="Test者"},
            };

            users.ForEach(i => context.Users.Add(i));
            context.SaveChanges();

            var goods = new List<GoodsDetail>
           {
               new GoodsDetail { GoodsName="LP359G",EffectiveDate=12, Units="KG"}, 
                    new GoodsDetail { GoodsName="LP360G",EffectiveDate=12, Units="KG" }, 
                    new GoodsDetail { GoodsName="LP361G",EffectiveDate=12, Units="KG" }, 
                    new GoodsDetail {   GoodsName="LP362G", EffectiveDate=12, Units="KG"},
                    new GoodsDetail { GoodsName="LP363G", EffectiveDate=12, Units="KG"},
                    new GoodsDetail {GoodsName="LP364G",EffectiveDate=12, Units="KG" }, 
                    new GoodsDetail { GoodsName="LP365G", EffectiveDate=12, Units="KG"}, 
                    new GoodsDetail { GoodsName="LP373G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP430G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP435G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP446G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP447G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP450G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP451G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP468G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP471G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP472G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP474G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP741G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP747G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP801G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP811G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP846G", EffectiveDate=12, Units="KG"} ,
                    new GoodsDetail { GoodsName="LP374G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP376G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP422G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP429G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP437G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP444G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP445G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP469G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP470G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP372G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP476G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP477G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP478G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP762G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP763G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP776G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP777G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP780G",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP781G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP763H",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP776H",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LG023G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LB620G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LB531G", EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LG008G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP463G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP467G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LB596G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LB597G", EffectiveDate=12, Units="KG"} ,                  
                    new GoodsDetail { GoodsName="LG009G",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP372R",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP834R",EffectiveDate=12, Units="KG"} , 
                    new GoodsDetail { GoodsName="LP463R",EffectiveDate=12, Units="KG" } , 
                    new GoodsDetail { GoodsName="LP471R",EffectiveDate=12, Units="KG"} , 
           };
            goods.ForEach(i => context.GoodsDetails.Add(i));
            context.SaveChanges();



            var mauns=new List<Manufacturer>{
            
               new Manufacturer{ ManufacturerName="新光"},
                new Manufacturer{ ManufacturerName="L&K"},
                 new Manufacturer{ ManufacturerName="三井上海"},
                  new Manufacturer{ ManufacturerName="三井日本"},
                   new Manufacturer{ ManufacturerName="凸版"},
                    new Manufacturer{ ManufacturerName="住山苏州"},
                      new Manufacturer{ ManufacturerName="大日本"},
                        new Manufacturer{ ManufacturerName="R材"},

            };
            mauns.ForEach(i=>context.Manufacturers.Add(i));
            context.SaveChanges();


            var products = new List<Product> 
                { 
                    new Product { ProductName="LP359G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10, CheckStatu="冻结"}, 
                    new Product { ProductName="LP360G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"}, 
                    new Product { ProductName="LP361G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"}, 
                    new Product {   ProductName="LP362G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"},
                    new Product { ProductName="LP363G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"},
                    new Product {ProductName="LP364G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="已检"}, 
                    new Product { ProductName="LP365G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="已检"}, 
                    new Product { ProductName="LP373G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10, CheckStatu="冻结" } , 
                    new Product { ProductName="LP430G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                    new Product { ProductName="LP435G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10, CheckStatu="冻结" } , 
                    new Product { ProductName="LP446G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10, CheckStatu="已检" } , 
                    new Product { ProductName="LP447G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                    new Product { ProductName="LP450G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                    new Product { ProductName="LP451G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                    new Product { ProductName="LP468G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                             new Product { ProductName="LP471G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 , CheckStatu="冻结"} , 
                                new Product { ProductName="LP472G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                   new Product { ProductName="LP474G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                      new Product { ProductName="LP741G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                         new Product { ProductName="LP747G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 

                                            new Product { ProductName="LP801G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                         new Product { ProductName="LP811G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                         new Product { ProductName="LP846G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } ,
                                          new Product { ProductName="LP374G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP376G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                            new Product { ProductName="LP422G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                             new Product { ProductName="LP429G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                              new Product { ProductName="LP437G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                               new Product { ProductName="LP444G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 

                                               new Product { ProductName="LP445G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 

                                            new Product { ProductName="LP469G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                            new Product { ProductName="LP470G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP372G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP476G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP477G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP478G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP762G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                           new Product { ProductName="LP763G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                              new Product { ProductName="LP776G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                 new Product { ProductName="LP777G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                    new Product { ProductName="LP780G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                       new Product { ProductName="LP781G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                          new Product { ProductName="LP763H",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                             new Product { ProductName="LP776H",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                new Product { ProductName="LG023G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 

                                                                   new Product { ProductName="LB620G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                   new Product { ProductName="LB531G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                   new Product { ProductName="LG008G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                    new Product { ProductName="LP463G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                     new Product { ProductName="LP467G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 

                                                                      new Product { ProductName="LB596G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                      new Product { ProductName="LB597G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                      new Product { ProductName="LB531G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                      new Product { ProductName="LG008G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                        new Product { ProductName="LG009G",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                          new Product { ProductName="LP372R",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                           new Product { ProductName="LP834R",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                            new Product { ProductName="LP463R",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                                                                             new Product { ProductName="LP471R",LotNum=" Lot1",ProductTime= DateTime.Now,Number=10,CheckTime=DateTime.Now,MaterialNo="料1",UnitNum=10 } , 
                };

            products.ForEach(s => context.Products.Add(s));
            context.SaveChanges();

            ///初始化货架类型
            var storageCategories = new List<StorageCategory>
            {
                new StorageCategory{ Category="移动", StorageNumber="A"},
                 new StorageCategory{ Category="移动", StorageNumber="B"},
                  new StorageCategory{ Category="移动", StorageNumber="C"},
                   new StorageCategory{ Category="移动", StorageNumber="D"},
                    new StorageCategory{ Category="移动", StorageNumber="E"},
                     new StorageCategory{ Category="移动", StorageNumber="F"},
                      new StorageCategory{ Category="移动", StorageNumber="G"},
                       new StorageCategory{ Category="移动", StorageNumber="H"},
                        new StorageCategory{ Category="大货架", StorageNumber="I"},
                         new StorageCategory{ Category="大货架", StorageNumber="J"},
                          new StorageCategory{ Category="大货架", StorageNumber="K"},
                           new StorageCategory{ Category="大货架", StorageNumber="L"},

                            new StorageCategory{ Category="大货架", StorageNumber="M"},
                          new StorageCategory{ Category="大货架", StorageNumber="N"},
                          new StorageCategory{ Category="大货架", StorageNumber="O"},
                              new StorageCategory{ Category="小货架", StorageNumber="P"},
                          new StorageCategory{ Category="小货架", StorageNumber="Q"},
                          new StorageCategory{ Category="小货架", StorageNumber="R"},
                               new StorageCategory{ Category="小货架", StorageNumber="S"},
                                    new StorageCategory{ Category="小货架", StorageNumber="T"},
            };

            storageCategories.ForEach(i => context.StorageCategorys.Add(i));
            context.SaveChanges();

            var locations = new List<StorageLocation>()
                {
                new StorageLocation{LocationName="A-1-1", CategoryName="A"},
                new StorageLocation{LocationName="A-1-2", CategoryName="A"},
                new StorageLocation{LocationName="A-1-3", CategoryName="A"},
                new StorageLocation{LocationName="A-1-4", CategoryName="A"},
                new StorageLocation{LocationName="A-1-5", CategoryName="A"},
                new StorageLocation{LocationName="A-1-6", CategoryName="A"},
                new StorageLocation{LocationName="A-1-7", CategoryName="A"},
                new StorageLocation{LocationName="A-1-8", CategoryName="A"},
                new StorageLocation{LocationName="A-1-9", CategoryName="A"},
                new StorageLocation{LocationName="A-2-1", CategoryName="A"},
                new StorageLocation{LocationName="A-2-2", CategoryName="A"},
                new StorageLocation{LocationName="A-2-3", CategoryName="A"},
                new StorageLocation{LocationName="A-2-4", CategoryName="A"},
                new StorageLocation{LocationName="A-2-5", CategoryName="A"},
                new StorageLocation{LocationName="A-2-6", CategoryName="A"},
                new StorageLocation{LocationName="A-2-7", CategoryName="A"},
                new StorageLocation{LocationName="A-2-8", CategoryName="A"},
                new StorageLocation{LocationName="A-2-9", CategoryName="A"},
                new StorageLocation{LocationName="A-3-1", CategoryName="A"},
                new StorageLocation{LocationName="A-3-2", CategoryName="A"},
                new StorageLocation{LocationName="A-3-3", CategoryName="A"},
                new StorageLocation{LocationName="A-3-4", CategoryName="A"},
                new StorageLocation{LocationName="A-3-5", CategoryName="A"},
                new StorageLocation{LocationName="A-3-6", CategoryName="A"},
                new StorageLocation{LocationName="A-3-7", CategoryName="A"},
                new StorageLocation{LocationName="A-3-8", CategoryName="A"},
                new StorageLocation{LocationName="A-3-9", CategoryName="A"},
                new StorageLocation{LocationName="A-4-1", CategoryName="A"},
                new StorageLocation{LocationName="A-4-2", CategoryName="A"},
                new StorageLocation{LocationName="A-4-3", CategoryName="A"},
                new StorageLocation{LocationName="A-4-4", CategoryName="A"},
                new StorageLocation{LocationName="A-4-5", CategoryName="A"},
                new StorageLocation{LocationName="A-4-6", CategoryName="A"},
                new StorageLocation{LocationName="A-4-7", CategoryName="A"},
                new StorageLocation{LocationName="A-4-8", CategoryName="A"},
                new StorageLocation{LocationName="A-4-9", CategoryName="A"},
                new StorageLocation{LocationName="B-1-1", CategoryName="B"},
                new StorageLocation{LocationName="B-1-2", CategoryName="B"},
                new StorageLocation{LocationName="B-1-3", CategoryName="B"},
                new StorageLocation{LocationName="B-1-4", CategoryName="B"},
                new StorageLocation{LocationName="B-1-5", CategoryName="B"},
                new StorageLocation{LocationName="B-1-6", CategoryName="B"},
                new StorageLocation{LocationName="B-1-7", CategoryName="B"},
                new StorageLocation{LocationName="B-1-8", CategoryName="B"},
                new StorageLocation{LocationName="B-1-9", CategoryName="B"},
                new StorageLocation{LocationName="B-2-1", CategoryName="B"},
                new StorageLocation{LocationName="B-2-2", CategoryName="B"},
                new StorageLocation{LocationName="B-2-3", CategoryName="B"},
                new StorageLocation{LocationName="B-2-4", CategoryName="B"},
                new StorageLocation{LocationName="B-2-5", CategoryName="B"},
                new StorageLocation{LocationName="B-2-6", CategoryName="B"},
                new StorageLocation{LocationName="B-2-7", CategoryName="B"},
                new StorageLocation{LocationName="B-2-8", CategoryName="B"},
                new StorageLocation{LocationName="B-2-9", CategoryName="B"},
                new StorageLocation{LocationName="B-3-1", CategoryName="B"},
                new StorageLocation{LocationName="B-3-2", CategoryName="B"},
                new StorageLocation{LocationName="B-3-3", CategoryName="B"},
                new StorageLocation{LocationName="B-3-4", CategoryName="B"},
                new StorageLocation{LocationName="B-3-5", CategoryName="B"},
                new StorageLocation{LocationName="B-3-6", CategoryName="B"},
                new StorageLocation{LocationName="B-3-7", CategoryName="B"},
                new StorageLocation{LocationName="B-3-8", CategoryName="B"},
                new StorageLocation{LocationName="B-3-9", CategoryName="B"},
                new StorageLocation{LocationName="B-4-1", CategoryName="B"},
                new StorageLocation{LocationName="B-4-2", CategoryName="B"},
                new StorageLocation{LocationName="B-4-3", CategoryName="B"},
                new StorageLocation{LocationName="B-4-4", CategoryName="B"},
                new StorageLocation{LocationName="B-4-5", CategoryName="B"},
                new StorageLocation{LocationName="B-4-6", CategoryName="B"},
                new StorageLocation{LocationName="B-4-7", CategoryName="B"},
                new StorageLocation{LocationName="B-4-8", CategoryName="B"},
                new StorageLocation{LocationName="B-4-9", CategoryName="B"},
                new StorageLocation{LocationName="C-1-1", CategoryName="C"},
                new StorageLocation{LocationName="C-1-2", CategoryName="C"},
                new StorageLocation{LocationName="C-1-3", CategoryName="C"},
                new StorageLocation{LocationName="C-1-4", CategoryName="C"},
                new StorageLocation{LocationName="C-1-5", CategoryName="C"},
                new StorageLocation{LocationName="C-1-6", CategoryName="C"},
                new StorageLocation{LocationName="C-1-7", CategoryName="C"},
                new StorageLocation{LocationName="C-1-8", CategoryName="C"},
                new StorageLocation{LocationName="C-1-9", CategoryName="C"},
                new StorageLocation{LocationName="C-2-1", CategoryName="C"},
                new StorageLocation{LocationName="C-2-2", CategoryName="C"},
                new StorageLocation{LocationName="C-2-3", CategoryName="C"},
                new StorageLocation{LocationName="C-2-4", CategoryName="C"},
                new StorageLocation{LocationName="C-2-5", CategoryName="C"},
                new StorageLocation{LocationName="C-2-6", CategoryName="C"},
                new StorageLocation{LocationName="C-2-7", CategoryName="C"},
                new StorageLocation{LocationName="C-2-8", CategoryName="C"},
                new StorageLocation{LocationName="C-2-9", CategoryName="C"},
                new StorageLocation{LocationName="C-3-1", CategoryName="C"},
                new StorageLocation{LocationName="C-3-2", CategoryName="C"},
                new StorageLocation{LocationName="C-3-3", CategoryName="C"},
                new StorageLocation{LocationName="C-3-4", CategoryName="C"},
                new StorageLocation{LocationName="C-3-5", CategoryName="C"},
                new StorageLocation{LocationName="C-3-6", CategoryName="C"},
                new StorageLocation{LocationName="C-3-7", CategoryName="C"},
                new StorageLocation{LocationName="C-3-8", CategoryName="C"},
                new StorageLocation{LocationName="C-3-9", CategoryName="C"},
                new StorageLocation{LocationName="C-4-1", CategoryName="C"},
                new StorageLocation{LocationName="C-4-2", CategoryName="C"},
                new StorageLocation{LocationName="C-4-3", CategoryName="C"},
                new StorageLocation{LocationName="C-4-4", CategoryName="C"},
                new StorageLocation{LocationName="C-4-5", CategoryName="C"},
                new StorageLocation{LocationName="C-4-6", CategoryName="C"},
                new StorageLocation{LocationName="C-4-7", CategoryName="C"},
                new StorageLocation{LocationName="C-4-8", CategoryName="C"},
                new StorageLocation{LocationName="C-4-9", CategoryName="C"},
                new StorageLocation{LocationName="D-1-1", CategoryName="D"},
                new StorageLocation{LocationName="D-1-2", CategoryName="D"},
                new StorageLocation{LocationName="D-1-3", CategoryName="D"},
                new StorageLocation{LocationName="D-1-4", CategoryName="D"},
                new StorageLocation{LocationName="D-1-5", CategoryName="D"},
                new StorageLocation{LocationName="D-1-6", CategoryName="D"},
                new StorageLocation{LocationName="D-1-7", CategoryName="D"},
                new StorageLocation{LocationName="D-1-8", CategoryName="D"},
                new StorageLocation{LocationName="D-1-9", CategoryName="D"},
                new StorageLocation{LocationName="D-2-1", CategoryName="D"},
                new StorageLocation{LocationName="D-2-2", CategoryName="D"},
                new StorageLocation{LocationName="D-2-3", CategoryName="D"},
                new StorageLocation{LocationName="D-2-4", CategoryName="D"},
                new StorageLocation{LocationName="D-2-5", CategoryName="D"},
                new StorageLocation{LocationName="D-2-6", CategoryName="D"},
                new StorageLocation{LocationName="D-2-7", CategoryName="D"},
                new StorageLocation{LocationName="D-2-8", CategoryName="D"},
                new StorageLocation{LocationName="D-2-9", CategoryName="D"},
                new StorageLocation{LocationName="D-3-1", CategoryName="D"},
                new StorageLocation{LocationName="D-3-2", CategoryName="D"},
                new StorageLocation{LocationName="D-3-3", CategoryName="D"},
                new StorageLocation{LocationName="D-3-4", CategoryName="D"},
                new StorageLocation{LocationName="D-3-5", CategoryName="D"},
                new StorageLocation{LocationName="D-3-6", CategoryName="D"},
                new StorageLocation{LocationName="D-3-7", CategoryName="D"},
                new StorageLocation{LocationName="D-3-8", CategoryName="D"},
                new StorageLocation{LocationName="D-3-9", CategoryName="D"},
                new StorageLocation{LocationName="D-4-1", CategoryName="D"},
                new StorageLocation{LocationName="D-4-2", CategoryName="D"},
                new StorageLocation{LocationName="D-4-3", CategoryName="D"},
                new StorageLocation{LocationName="D-4-4", CategoryName="D"},
                new StorageLocation{LocationName="D-4-5", CategoryName="D"},
                new StorageLocation{LocationName="D-4-6", CategoryName="D"},
                new StorageLocation{LocationName="D-4-7", CategoryName="D"},
                new StorageLocation{LocationName="D-4-8", CategoryName="D"},
                new StorageLocation{LocationName="D-4-9", CategoryName="D"},
                new StorageLocation{LocationName="E-1-1", CategoryName="E"},
                new StorageLocation{LocationName="E-1-2", CategoryName="E"},
                new StorageLocation{LocationName="E-1-3", CategoryName="E"},
                new StorageLocation{LocationName="E-1-4", CategoryName="E"},
                new StorageLocation{LocationName="E-1-5", CategoryName="E"},
                new StorageLocation{LocationName="E-1-6", CategoryName="E"},
                new StorageLocation{LocationName="E-1-7", CategoryName="E"},
                new StorageLocation{LocationName="E-1-8", CategoryName="E"},
                new StorageLocation{LocationName="E-1-9", CategoryName="E"},
                new StorageLocation{LocationName="E-2-1", CategoryName="E"},
                new StorageLocation{LocationName="E-2-2", CategoryName="E"},
                new StorageLocation{LocationName="E-2-3", CategoryName="E"},
                new StorageLocation{LocationName="E-2-4", CategoryName="E"},
                new StorageLocation{LocationName="E-2-5", CategoryName="E"},
                new StorageLocation{LocationName="E-2-6", CategoryName="E"},
                new StorageLocation{LocationName="E-2-7", CategoryName="E"},
                new StorageLocation{LocationName="E-2-8", CategoryName="E"},
                new StorageLocation{LocationName="E-2-9", CategoryName="E"},
                new StorageLocation{LocationName="E-3-1", CategoryName="E"},
                new StorageLocation{LocationName="E-3-2", CategoryName="E"},
                new StorageLocation{LocationName="E-3-3", CategoryName="E"},
                new StorageLocation{LocationName="E-3-4", CategoryName="E"},
                new StorageLocation{LocationName="E-3-5", CategoryName="E"},
                new StorageLocation{LocationName="E-3-6", CategoryName="E"},
                new StorageLocation{LocationName="E-3-7", CategoryName="E"},
                new StorageLocation{LocationName="E-3-8", CategoryName="E"},
                new StorageLocation{LocationName="E-3-9", CategoryName="E"},
                new StorageLocation{LocationName="E-4-1", CategoryName="E"},
                new StorageLocation{LocationName="E-4-2", CategoryName="E"},
                new StorageLocation{LocationName="E-4-3", CategoryName="E"},
                new StorageLocation{LocationName="E-4-4", CategoryName="E"},
                new StorageLocation{LocationName="E-4-5", CategoryName="E"},
                new StorageLocation{LocationName="E-4-6", CategoryName="E"},
                new StorageLocation{LocationName="E-4-7", CategoryName="E"},
                new StorageLocation{LocationName="E-4-8", CategoryName="E"},
                new StorageLocation{LocationName="E-4-9", CategoryName="E"},
                new StorageLocation{LocationName="F-1-1", CategoryName="F"},
                new StorageLocation{LocationName="F-1-2", CategoryName="F"},
                new StorageLocation{LocationName="F-1-3", CategoryName="F"},
                new StorageLocation{LocationName="F-1-4", CategoryName="F"},
                new StorageLocation{LocationName="F-1-5", CategoryName="F"},
                new StorageLocation{LocationName="F-1-6", CategoryName="F"},
                new StorageLocation{LocationName="F-1-7", CategoryName="F"},
                new StorageLocation{LocationName="F-1-8", CategoryName="F"},
                new StorageLocation{LocationName="F-1-9", CategoryName="F"},
                new StorageLocation{LocationName="F-2-1", CategoryName="F"},
                new StorageLocation{LocationName="F-2-2", CategoryName="F"},
                new StorageLocation{LocationName="F-2-3", CategoryName="F"},
                new StorageLocation{LocationName="F-2-4", CategoryName="F"},
                new StorageLocation{LocationName="F-2-5", CategoryName="F"},
                new StorageLocation{LocationName="F-2-6", CategoryName="F"},
                new StorageLocation{LocationName="F-2-7", CategoryName="F"},
                new StorageLocation{LocationName="F-2-8", CategoryName="F"},
                new StorageLocation{LocationName="F-2-9", CategoryName="F"},
                new StorageLocation{LocationName="F-3-1", CategoryName="F"},
                new StorageLocation{LocationName="F-3-2", CategoryName="F"},
                new StorageLocation{LocationName="F-3-3", CategoryName="F"},
                new StorageLocation{LocationName="F-3-4", CategoryName="F"},
                new StorageLocation{LocationName="F-3-5", CategoryName="F"},
                new StorageLocation{LocationName="F-3-6", CategoryName="F"},
                new StorageLocation{LocationName="F-3-7", CategoryName="F"},
                new StorageLocation{LocationName="F-3-8", CategoryName="F"},
                new StorageLocation{LocationName="F-3-9", CategoryName="F"},
                new StorageLocation{LocationName="F-4-1", CategoryName="F"},
                new StorageLocation{LocationName="F-4-2", CategoryName="F"},
                new StorageLocation{LocationName="F-4-3", CategoryName="F"},
                new StorageLocation{LocationName="F-4-4", CategoryName="F"},
                new StorageLocation{LocationName="F-4-5", CategoryName="F"},
                new StorageLocation{LocationName="F-4-6", CategoryName="F"},
                new StorageLocation{LocationName="F-4-7", CategoryName="F"},
                new StorageLocation{LocationName="F-4-8", CategoryName="F"},
                new StorageLocation{LocationName="F-4-9", CategoryName="F"},
                new StorageLocation{LocationName="G-1-1", CategoryName="G"},
                new StorageLocation{LocationName="G-1-2", CategoryName="G"},
                new StorageLocation{LocationName="G-1-3", CategoryName="G"},
                new StorageLocation{LocationName="G-1-4", CategoryName="G"},
                new StorageLocation{LocationName="G-1-5", CategoryName="G"},
                new StorageLocation{LocationName="G-1-6", CategoryName="G"},
                new StorageLocation{LocationName="G-1-7", CategoryName="G"},
                new StorageLocation{LocationName="G-1-8", CategoryName="G"},
                new StorageLocation{LocationName="G-1-9", CategoryName="G"},
                new StorageLocation{LocationName="G-2-1", CategoryName="G"},
                new StorageLocation{LocationName="G-2-2", CategoryName="G"},
                new StorageLocation{LocationName="G-2-3", CategoryName="G"},
                new StorageLocation{LocationName="G-2-4", CategoryName="G"},
                new StorageLocation{LocationName="G-2-5", CategoryName="G"},
                new StorageLocation{LocationName="G-2-6", CategoryName="G"},
                new StorageLocation{LocationName="G-2-7", CategoryName="G"},
                new StorageLocation{LocationName="G-2-8", CategoryName="G"},
                new StorageLocation{LocationName="G-2-9", CategoryName="G"},
                new StorageLocation{LocationName="G-3-1", CategoryName="G"},
                new StorageLocation{LocationName="G-3-2", CategoryName="G"},
                new StorageLocation{LocationName="G-3-3", CategoryName="G"},
                new StorageLocation{LocationName="G-3-4", CategoryName="G"},
                new StorageLocation{LocationName="G-3-5", CategoryName="G"},
                new StorageLocation{LocationName="G-3-6", CategoryName="G"},
                new StorageLocation{LocationName="G-3-7", CategoryName="G"},
                new StorageLocation{LocationName="G-3-8", CategoryName="G"},
                new StorageLocation{LocationName="G-3-9", CategoryName="G"},
                new StorageLocation{LocationName="G-4-1", CategoryName="G"},
                new StorageLocation{LocationName="G-4-2", CategoryName="G"},
                new StorageLocation{LocationName="G-4-3", CategoryName="G"},
                new StorageLocation{LocationName="G-4-4", CategoryName="G"},
                new StorageLocation{LocationName="G-4-5", CategoryName="G"},
                new StorageLocation{LocationName="G-4-6", CategoryName="G"},
                new StorageLocation{LocationName="G-4-7", CategoryName="G"},
                new StorageLocation{LocationName="G-4-8", CategoryName="G"},
                new StorageLocation{LocationName="G-4-9", CategoryName="G"},
                new StorageLocation{LocationName="H-1-1", CategoryName="H"},
                new StorageLocation{LocationName="H-1-2", CategoryName="H"},
                new StorageLocation{LocationName="H-1-3", CategoryName="H"},
                new StorageLocation{LocationName="H-2-1", CategoryName="H"},
                new StorageLocation{LocationName="H-2-2", CategoryName="H"},
                new StorageLocation{LocationName="H-2-3", CategoryName="H"},
                new StorageLocation{LocationName="H-3-1", CategoryName="H"},
                new StorageLocation{LocationName="H-3-2", CategoryName="H"},
                new StorageLocation{LocationName="H-3-3", CategoryName="H"},
                new StorageLocation{LocationName="H-4-1", CategoryName="H"},
                new StorageLocation{LocationName="H-4-2", CategoryName="H"},
                new StorageLocation{LocationName="H-4-3", CategoryName="H"},
                new StorageLocation{LocationName="I-1-1", CategoryName="I"},
                new StorageLocation{LocationName="I-1-2", CategoryName="I"},
                new StorageLocation{LocationName="I-1-3", CategoryName="I"},
                new StorageLocation{LocationName="I-1-4", CategoryName="I"},
                new StorageLocation{LocationName="I-1-5", CategoryName="I"},
                new StorageLocation{LocationName="I-1-6", CategoryName="I"},
                new StorageLocation{LocationName="I-2-1", CategoryName="I"},
                new StorageLocation{LocationName="I-2-2", CategoryName="I"},
                new StorageLocation{LocationName="I-2-3", CategoryName="I"},
                new StorageLocation{LocationName="I-2-4", CategoryName="I"},
                new StorageLocation{LocationName="I-2-5", CategoryName="I"},
                new StorageLocation{LocationName="I-2-6", CategoryName="I"},
                new StorageLocation{LocationName="I-3-1", CategoryName="I"},
                new StorageLocation{LocationName="I-3-2", CategoryName="I"},
                new StorageLocation{LocationName="I-3-3", CategoryName="I"},
                new StorageLocation{LocationName="I-3-4", CategoryName="I"},
                new StorageLocation{LocationName="I-3-5", CategoryName="I"},
                new StorageLocation{LocationName="I-3-6", CategoryName="I"},
                new StorageLocation{LocationName="J-1-1", CategoryName="J"},
                new StorageLocation{LocationName="J-1-2", CategoryName="J"},
                new StorageLocation{LocationName="J-1-3", CategoryName="J"},
                new StorageLocation{LocationName="J-1-4", CategoryName="J"},
                new StorageLocation{LocationName="J-1-5", CategoryName="J"},
                new StorageLocation{LocationName="J-1-6", CategoryName="J"},
                new StorageLocation{LocationName="J-2-1", CategoryName="J"},
                new StorageLocation{LocationName="J-2-2", CategoryName="J"},
                new StorageLocation{LocationName="J-2-3", CategoryName="J"},
                new StorageLocation{LocationName="J-2-4", CategoryName="J"},
                new StorageLocation{LocationName="J-2-5", CategoryName="J"},
                new StorageLocation{LocationName="J-2-6", CategoryName="J"},
                new StorageLocation{LocationName="J-3-1", CategoryName="J"},
                new StorageLocation{LocationName="J-3-2", CategoryName="J"},
                new StorageLocation{LocationName="J-3-3", CategoryName="J"},
                new StorageLocation{LocationName="J-3-4", CategoryName="J"},
                new StorageLocation{LocationName="J-3-5", CategoryName="J"},
                new StorageLocation{LocationName="J-3-6", CategoryName="J"},
                new StorageLocation{LocationName="K-1-1", CategoryName="K"},
                new StorageLocation{LocationName="K-1-2", CategoryName="K"},
                new StorageLocation{LocationName="K-1-3", CategoryName="K"},
                new StorageLocation{LocationName="K-1-4", CategoryName="K"},
                new StorageLocation{LocationName="K-1-5", CategoryName="K"},
                new StorageLocation{LocationName="K-1-6", CategoryName="K"},
                new StorageLocation{LocationName="K-2-1", CategoryName="K"},
                new StorageLocation{LocationName="K-2-2", CategoryName="K"},
                new StorageLocation{LocationName="K-2-3", CategoryName="K"},
                new StorageLocation{LocationName="K-2-4", CategoryName="K"},
                new StorageLocation{LocationName="K-2-5", CategoryName="K"},
                new StorageLocation{LocationName="K-2-6", CategoryName="K"},
                new StorageLocation{LocationName="K-3-1", CategoryName="K"},
                new StorageLocation{LocationName="K-3-2", CategoryName="K"},
                new StorageLocation{LocationName="K-3-3", CategoryName="K"},
                new StorageLocation{LocationName="K-3-4", CategoryName="K"},
                new StorageLocation{LocationName="K-3-5", CategoryName="K"},
                new StorageLocation{LocationName="K-3-6", CategoryName="K"},
                new StorageLocation{LocationName="L-1-1", CategoryName="L"},
                new StorageLocation{LocationName="L-1-2", CategoryName="L"},
                new StorageLocation{LocationName="L-1-3", CategoryName="L"},
                new StorageLocation{LocationName="L-1-4", CategoryName="L"},
                new StorageLocation{LocationName="L-1-5", CategoryName="L"},
                new StorageLocation{LocationName="L-1-6", CategoryName="L"},
                new StorageLocation{LocationName="L-2-1", CategoryName="L"},
                new StorageLocation{LocationName="L-2-2", CategoryName="L"},
                new StorageLocation{LocationName="L-2-3", CategoryName="L"},
                new StorageLocation{LocationName="L-2-4", CategoryName="L"},
                new StorageLocation{LocationName="L-2-5", CategoryName="L"},
                new StorageLocation{LocationName="L-2-6", CategoryName="L"},
                new StorageLocation{LocationName="L-3-1", CategoryName="L"},
                new StorageLocation{LocationName="L-3-2", CategoryName="L"},
                new StorageLocation{LocationName="L-3-3", CategoryName="L"},
                new StorageLocation{LocationName="L-3-4", CategoryName="L"},
                new StorageLocation{LocationName="L-3-5", CategoryName="L"},
                new StorageLocation{LocationName="L-3-6", CategoryName="L"},
                new StorageLocation{LocationName="M-1-1", CategoryName="M"},
                new StorageLocation{LocationName="M-1-2", CategoryName="M"},
                new StorageLocation{LocationName="M-1-3", CategoryName="M"},
                new StorageLocation{LocationName="M-1-4", CategoryName="M"},
                new StorageLocation{LocationName="M-1-5", CategoryName="M"},
                new StorageLocation{LocationName="M-1-6", CategoryName="M"},
                new StorageLocation{LocationName="M-2-1", CategoryName="M"},
                new StorageLocation{LocationName="M-2-2", CategoryName="M"},
                new StorageLocation{LocationName="M-2-3", CategoryName="M"},
                new StorageLocation{LocationName="M-2-4", CategoryName="M"},
                new StorageLocation{LocationName="M-2-5", CategoryName="M"},
                new StorageLocation{LocationName="M-2-6", CategoryName="M"},
                new StorageLocation{LocationName="M-3-1", CategoryName="M"},
                new StorageLocation{LocationName="M-3-2", CategoryName="M"},
                new StorageLocation{LocationName="M-3-3", CategoryName="M"},
                new StorageLocation{LocationName="M-3-4", CategoryName="M"},
                new StorageLocation{LocationName="M-3-5", CategoryName="M"},
                new StorageLocation{LocationName="M-3-6", CategoryName="M"},
                new StorageLocation{LocationName="N-1-1", CategoryName="N"},
                new StorageLocation{LocationName="N-1-2", CategoryName="N"},
                new StorageLocation{LocationName="N-1-3", CategoryName="N"},
                new StorageLocation{LocationName="N-1-4", CategoryName="N"},
                new StorageLocation{LocationName="N-1-5", CategoryName="N"},
                new StorageLocation{LocationName="N-1-6", CategoryName="N"},
                new StorageLocation{LocationName="N-2-1", CategoryName="N"},
                new StorageLocation{LocationName="N-2-2", CategoryName="N"},
                new StorageLocation{LocationName="N-2-3", CategoryName="N"},
                new StorageLocation{LocationName="N-2-4", CategoryName="N"},
                new StorageLocation{LocationName="N-2-5", CategoryName="N"},
                new StorageLocation{LocationName="N-2-6", CategoryName="N"},
                new StorageLocation{LocationName="N-3-1", CategoryName="N"},
                new StorageLocation{LocationName="N-3-2", CategoryName="N"},
                new StorageLocation{LocationName="N-3-3", CategoryName="N"},
                new StorageLocation{LocationName="N-3-4", CategoryName="N"},
                new StorageLocation{LocationName="N-3-5", CategoryName="N"},
                new StorageLocation{LocationName="N-3-6", CategoryName="N"},
                new StorageLocation{LocationName="O-1-1", CategoryName="O"},
                new StorageLocation{LocationName="O-1-2", CategoryName="O"},
                new StorageLocation{LocationName="O-1-3", CategoryName="O"},
                new StorageLocation{LocationName="O-1-4", CategoryName="O"},
                new StorageLocation{LocationName="O-1-5", CategoryName="O"},
                new StorageLocation{LocationName="O-1-6", CategoryName="O"},
                new StorageLocation{LocationName="O-2-1", CategoryName="O"},
                new StorageLocation{LocationName="O-2-2", CategoryName="O"},
                new StorageLocation{LocationName="O-2-3", CategoryName="O"},
                new StorageLocation{LocationName="O-2-4", CategoryName="O"},
                new StorageLocation{LocationName="O-2-5", CategoryName="O"},
                new StorageLocation{LocationName="O-2-6", CategoryName="O"},
                new StorageLocation{LocationName="O-3-1", CategoryName="O"},
                new StorageLocation{LocationName="O-3-2", CategoryName="O"},
                new StorageLocation{LocationName="O-3-3", CategoryName="O"},
                new StorageLocation{LocationName="O-3-4", CategoryName="O"},
                new StorageLocation{LocationName="O-3-5", CategoryName="O"},
                new StorageLocation{LocationName="O-3-6", CategoryName="O"},
                new StorageLocation{LocationName="P-1-1", CategoryName="P"},
                new StorageLocation{LocationName="P-1-2", CategoryName="P"},
                new StorageLocation{LocationName="P-1-3", CategoryName="P"},
                new StorageLocation{LocationName="P-1-4", CategoryName="P"},
                new StorageLocation{LocationName="P-2-1", CategoryName="P"},
                new StorageLocation{LocationName="P-2-2", CategoryName="P"},
                new StorageLocation{LocationName="P-2-3", CategoryName="P"},
                new StorageLocation{LocationName="P-2-4", CategoryName="P"},
                new StorageLocation{LocationName="P-3-1", CategoryName="P"},
                new StorageLocation{LocationName="P-3-2", CategoryName="P"},
                new StorageLocation{LocationName="P-3-3", CategoryName="P"},
                new StorageLocation{LocationName="P-3-4", CategoryName="P"},
                new StorageLocation{LocationName="P-4-1", CategoryName="P"},
                new StorageLocation{LocationName="P-4-2", CategoryName="P"},
                new StorageLocation{LocationName="P-4-3", CategoryName="P"},
                new StorageLocation{LocationName="P-4-4", CategoryName="P"},
                new StorageLocation{LocationName="Q-1-1", CategoryName="Q"},
                new StorageLocation{LocationName="Q-1-2", CategoryName="Q"},
                new StorageLocation{LocationName="Q-1-3", CategoryName="Q"},
                new StorageLocation{LocationName="Q-1-4", CategoryName="Q"},
                new StorageLocation{LocationName="Q-2-1", CategoryName="Q"},
                new StorageLocation{LocationName="Q-2-2", CategoryName="Q"},
                new StorageLocation{LocationName="Q-2-3", CategoryName="Q"},
                new StorageLocation{LocationName="Q-2-4", CategoryName="Q"},
                new StorageLocation{LocationName="Q-3-1", CategoryName="Q"},
                new StorageLocation{LocationName="Q-3-2", CategoryName="Q"},
                new StorageLocation{LocationName="Q-3-3", CategoryName="Q"},
                new StorageLocation{LocationName="Q-3-4", CategoryName="Q"},
                new StorageLocation{LocationName="Q-4-1", CategoryName="Q"},
                new StorageLocation{LocationName="Q-4-2", CategoryName="Q"},
                new StorageLocation{LocationName="Q-4-3", CategoryName="Q"},
                new StorageLocation{LocationName="Q-4-4", CategoryName="Q"},
                new StorageLocation{LocationName="R-1-1", CategoryName="R"},
                new StorageLocation{LocationName="R-1-2", CategoryName="R"},
                new StorageLocation{LocationName="R-1-3", CategoryName="R"},
                new StorageLocation{LocationName="R-1-4", CategoryName="R"},
                new StorageLocation{LocationName="R-2-1", CategoryName="R"},
                new StorageLocation{LocationName="R-2-2", CategoryName="R"},
                new StorageLocation{LocationName="R-2-3", CategoryName="R"},
                new StorageLocation{LocationName="R-2-4", CategoryName="R"},
                new StorageLocation{LocationName="R-3-1", CategoryName="R"},
                new StorageLocation{LocationName="R-3-2", CategoryName="R"},
                new StorageLocation{LocationName="R-3-3", CategoryName="R"},
                new StorageLocation{LocationName="R-3-4", CategoryName="R"},
                new StorageLocation{LocationName="R-4-1", CategoryName="R"},
                new StorageLocation{LocationName="R-4-2", CategoryName="R"},
                new StorageLocation{LocationName="R-4-3", CategoryName="R"},
                new StorageLocation{LocationName="R-4-4", CategoryName="R"},
                new StorageLocation{LocationName="S-1-1", CategoryName="S"},
                new StorageLocation{LocationName="S-1-2", CategoryName="S"},
                new StorageLocation{LocationName="S-1-3", CategoryName="S"},
                new StorageLocation{LocationName="S-1-4", CategoryName="S"},
                new StorageLocation{LocationName="S-2-1", CategoryName="S"},
                new StorageLocation{LocationName="S-2-2", CategoryName="S"},
                new StorageLocation{LocationName="S-2-3", CategoryName="S"},
                new StorageLocation{LocationName="S-2-4", CategoryName="S"},
                new StorageLocation{LocationName="S-3-1", CategoryName="S"},
                new StorageLocation{LocationName="S-3-2", CategoryName="S"},
                new StorageLocation{LocationName="S-3-3", CategoryName="S"},
                new StorageLocation{LocationName="S-3-4", CategoryName="S"},
                new StorageLocation{LocationName="S-4-1", CategoryName="S"},
                new StorageLocation{LocationName="S-4-2", CategoryName="S"},
                new StorageLocation{LocationName="S-4-3", CategoryName="S"},
                new StorageLocation{LocationName="S-4-4", CategoryName="S"},
                new StorageLocation{LocationName="T-1-1", CategoryName="T"},
                new StorageLocation{LocationName="T-1-2", CategoryName="T"},
                new StorageLocation{LocationName="T-1-3", CategoryName="T"},
                new StorageLocation{LocationName="T-1-4", CategoryName="T"},
                new StorageLocation{LocationName="T-2-1", CategoryName="T"},
                new StorageLocation{LocationName="T-2-2", CategoryName="T"},
                new StorageLocation{LocationName="T-2-3", CategoryName="T"},
                new StorageLocation{LocationName="T-2-4", CategoryName="T"},
                new StorageLocation{LocationName="T-3-1", CategoryName="T"},
                new StorageLocation{LocationName="T-3-2", CategoryName="T"},
                new StorageLocation{LocationName="T-3-3", CategoryName="T"},
                new StorageLocation{LocationName="T-3-4", CategoryName="T"},
                new StorageLocation{LocationName="T-4-1", CategoryName="T"},
                new StorageLocation{LocationName="T-4-2", CategoryName="T"},
                new StorageLocation{LocationName="T-4-3", CategoryName="T"},
                new StorageLocation{LocationName="T-4-4", CategoryName="T"},
                };

            locations.ForEach(i => context.StorageLocations.Add(i));
            context.SaveChanges();


            var checkrecords = new List<CheckRecord>{
           
            new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 1", ManufacturerName="新光", Number=20, ProductName="LP811G"},
             new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 2", ManufacturerName="新光", Number=20, ProductName="LP776H"},
              new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 3", ManufacturerName="新光", Number=20, ProductName="LP811G"},
               new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 4", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 5", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                 new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 6", ManufacturerName="新光", Number=20, ProductName="LG008G"},
                  new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 7", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                   new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 8", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                    new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 9", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                     new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 10", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                      new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 11", ManufacturerName="新光", Number=20, ProductName="LP834R"},
                       new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 12", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                        new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 13", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                         new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 14", ManufacturerName="新光", Number=20, ProductName="LP834R"},
                          new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 15", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                           new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 16", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                            new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 17", ManufacturerName="新光", Number=20, ProductName="LP811G"},
                             new CheckRecord{ CheckTime=DateTime.Now, LocationName="T-3-3", LotNum="lot 18", ManufacturerName="新光", Number=20, ProductName="LP811G"},

           };
            checkrecords.ForEach(i => context.CheckRecords.Add(i));
            context.SaveChanges();

            var imports = new List<ImportStorage>{
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 1", ManufacturerName="凸版", MaterialNo="料号1", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 2", ManufacturerName="凸版", MaterialNo="料号2", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 3", ManufacturerName="凸版", MaterialNo="料号3", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 4", ManufacturerName="凸版", MaterialNo="料号4", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 5", ManufacturerName="凸版", MaterialNo="料号5", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 6", ManufacturerName="新光", MaterialNo="料号6", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 7", ManufacturerName="凸版", MaterialNo="料号7", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 8", ManufacturerName="凸版", MaterialNo="料号8", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20}, 
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 9", ManufacturerName="凸版", MaterialNo="料号9", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 10", ManufacturerName="凸版", MaterialNo="料号10", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 11", ManufacturerName="凸版", MaterialNo="料号11", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
                     new ImportStorage{ ArrivalTime=DateTime.Now, LocationName="T-1-1", LotNum="lot 12", ManufacturerName="凸版", MaterialNo="料号12", Number=10, ProductName="LP811G", ProductTime=DateTime.Now, UnitNum=20},
            };
            imports.ForEach(i=>context.ImportStorages.Add(i));
            context.SaveChanges();

            var exports = new List<ExportStorage>
            {
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 1", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 2", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 3", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 4", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 5", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 6", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 7", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 8", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 9", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 10", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 11", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
                new ExportStorage{ ExpNum=100, ExpTime=DateTime.Now, LocationName="R-3-4", LotNumber="lot 12", ManufacturerName="凸版", ProductName="LP811G", UnitNum=11},
            };

            exports.ForEach(i => context.ExportStorages.Add(i));
            context.SaveChanges();

        }
    }
}
